src/Entity/OrderItem.php
<?php

namespace App\Entity;

use App\Repository\OrderItemRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OrderItemRepository::class)]
class OrderItem
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(targetEntity: Book::class)]
    #[ORM\JoinColumn(nullable: false)]
    private $book;
    
    #[ORM\ManyToOne(targetEntity: Order::class, inversedBy: "orderItems")]
    #[ORM\JoinColumn(nullable: false)]
    private $orderRef;

    #[ORM\Column]
    private ?int $quantity = null;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBook(): ?Book
    {
        return $this->book;
    }

    public function setBook(?Book $Book): self
    {
        $this->book = $Book;

        return $this;
    }


    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function equals(OrderItem $item): bool
    {
        return $this->getBook()->getId() === $item->getBook()->getId();
    }

    public function getOrderRef(): ?Order
    {
        return $this->orderRef;
    }

    public function setOrderRef(?Order $orderRef): self
    {
        $this->orderRef = $orderRef;

        return $this;
    }

    public function getTotal(): float
    {
    return $this->getBook()->getPrice() * $this->getQuantity();
    }
}

src/Form/CartType.php
<?php

namespace App\Form;

use App\Entity\Order;
use App\Form\EventListener\ClearCartListener;
use App\Form\EventListener\RemoveCartListener;
use Symfony\Component\ErrorHandler\Debug;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CartType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
        ->add('orderItems', CollectionType::class, [
            'entry_type' => CartItemType::class
        ])
        ->add('save', SubmitType::class)
        ->add('clear', SubmitType::class)
        ;
        $builder->addEventSubscriber(new RemoveCartListener());
        $builder->addEventSubscriber(new ClearCartListener());
        Debug::enable();
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Order::class,
        ]);
    }
}

src/Controller/CartController.php
<?php

namespace App\Controller;

use App\Form\CartType;
use App\Manager\CartManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route(path:'/cart')]
class CartController extends AbstractController
{

    #[Route('/', name: 'app_cart')]
    public function index(CartManager $cartManager, Request $request): Response
    {
        $cart = $cartManager->getCurrentCart();

        $form = $this->createForm(CartType::class, $cart);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $cart->setUpdatedAt(new \DateTime());
            $cartManager->save($cart);

            return $this->redirectToRoute('app_cart');
        }

        return $this->render('cart/index.html.twig', [
            'cart' => $cart,
            'form' => $form->createView()
        ]);
    }
    }

?>

templates/cart/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}User cart!{% endblock %}

{% block body %}
    <div class="container">
    <div class="row">
    <div class="col-md-8">
    {{ form_start(form) }}
    <div class="card">
        <div class="card-header bg-dark text-white d-flex">
            <h5>Items</h5>
            <div class="ml-auto">
                {{ form_widget(form.save, {'attr': {'class': 'btn btn-warning'}}) }}
                {{ form_widget(form.clear, {'attr': {'class': 'btn btn-light'}}) }}
            </div>
        </div>
        <ul class="list-group list-group-flush">
            {{ form_start(form) }}
            {% for item in form.orderItems %}
                <li class="list-group-item d-flex">
                    <div class="flex-fill mr-2">
                        <img src="{{ asset('img/' ~ item.vars.data.book.photo) }}" width="64" alt="Product image">
                    </div>
                    <div class="flex-fill mr-2">
                        <h5 class="mt-0 mb-0">{{ item.vars.data.book.title }}</h5>
                        <div class="form-inline mt-2">
                            <div class="form-inline mt-2">
                                <div class="form-group mb-0 mr-2">
                                    {{ form_widget(item.quantity, {
                                        'attr': {
                                            'class': 'form-control form-control-sm ' ~ (item.quantity.vars.valid ? '' : 'is-invalid')
                                        }
                                    }) }}
                                    <div class="invalid-feedback">
                                        {{ form_errors(item.quantity) }}
                                    </div>
                                </div>
                            {{ form_widget(item.remove, {'attr': {'class': 'btn btn-dark btn-sm'}}) }}
                        </div>
                    </div>
                    <div class="flex-fill mr-2 text-right">
                        <b>{{ item.vars.data.book.price }} €</b>
                    </div>
                </li>
            {% endfor %}
            {{ form_end(form) }}
        </ul>
    </div>
    {{ form_end(form, {'render_rest': false}) }}
    </div>
            <div class="col-md-4">
                <div class="card mt-4 mt-md-0">
                    <h5 class="card-header bg-dark text-white">Summary</h5>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item d-flex justify-content-between">
                            <div><b>Total</b></div>
                            <span><b>{{ cart.total }} €</b></span>
                        </li>
                    </ul>
                    <div class="card-body">
                        <a href="#" class="btn btn-warning w-100">Checkout</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}